# made with reference: https://github.com/hack4impact-uiuc/globalgiving-tool/blob/master/.circleci/config.yml

version: 2
jobs:
  lint: # linting job; testing job needs to be added when we have stuff to test
    docker:
      # python project; we need a browser and geckodriver to render webpages
      - image: circleci/python:3.7
    steps:
      - checkout # get commit to test from repo
      - run:
          command: |
            cd src
            pip install -r requirements.txt --user
            pip install -r requirements-dev.txt --user
            /home/circleci/.local/bin/black . --check
            # basically: go into src, install all requirements, check format with black
  test:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          command: |
            cd src
            pip install -r requirements.txt --user
            pip install -r requirements-dev.txt --user
            /home/circleci/.local/bin/pytest

workflows:
  version: 2
  build-test:
    jobs:
      - lint
      # - test
